server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/boot_test?serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
jwt:
    secret:
        key:


cloud:
    aws:
        s3:
            bucket: plus-bucket
        stack.auto: false
        region.static: ap-northeast-2
